/**
 *
 * $Id$
 */
package tmdl.scenario.validation;

import tmdl.library.Block;

import tmdl.scenario.Variant;

/**
 * A sample validator interface for {@link tmdl.scenario.BlockRealization}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockRealizationValidator {
	boolean validate();

	boolean validateBlock(Block value);
	boolean validateVariant(Variant value);
}
