/**
 *
 * $Id$
 */
package tmdl.scenario.validation;

import org.eclipse.emf.common.util.EList;

import tmdl.library.TemplateComposite;

import tmdl.scenario.BlockRealization;

/**
 * A sample validator interface for {@link tmdl.scenario.VariantComposite}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VariantCompositeValidator {
	boolean validate();

	boolean validateTemplate(TemplateComposite value);
	boolean validateRealizations(EList<BlockRealization> value);
}
