<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sant" nsURI="http://www.modelspartiti.org/templates/san/sant"
    nsPrefix="sant">
  <eClassifiers xsi:type="ecore:EClass" name="SANT" eSuperTypes="tmdl.ecore#//core/TemplateModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templatePlaces" upperBound="-1"
        eType="#//PlaceTemplate" containment="true" eKeys="san.ecore#//NamedElement/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
        eType="ecore:EClass san.ecore#//Place" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityTemplates" upperBound="-1"
        eType="#//ActivityTemplate" containment="true" eKeys="san.ecore#//NamedElement/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass tmdl.ecore#//core/Parameter" containment="true" eKeys="tmdl.ecore#//core/Parameter/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalVariables" upperBound="-1"
        eType="ecore:EClass san.ecore#//GlobalVariable" containment="true" eKeys="san.ecore#//NamedElement/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customType" upperBound="-1"
        eType="ecore:EClass san.ecore#//CustomTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gates" upperBound="-1"
        eType="#//GateTemplate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arcs" upperBound="-1" eType="#//ArcTemplate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceTemplate" eSuperTypes="san.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" lowerBound="1"
        eType="ecore:EClass tmdl.ecore#//core/Multiplicity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marking" upperBound="-1"
        eType="#//MarkingTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityRangeOperator" eSuperTypes="tmdl.ecore#//core/Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityTemplate" abstract="true" eSuperTypes="san.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="casesTemplate" lowerBound="1"
        eType="#//CasesSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasesSpecification" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CasesSpecificationConcrete" eSuperTypes="#//CasesSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" lowerBound="1" upperBound="-1"
        eType="ecore:EClass san.ecore#//Case" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasesSpecificationArray" eSuperTypes="#//CasesSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numCases" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p" lowerBound="1" upperBound="-1"
        eType="ecore:EClass san.ecore#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasesSpecificationParametric" eSuperTypes="#//CasesSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="ecore:EClass tmdl.ecore#//core/Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p" lowerBound="1" upperBound="-1"
        eType="ecore:EClass san.ecore#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasesSpecificationProbabilityArray"
      eSuperTypes="#//CasesSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="caseParameter" lowerBound="1"
        eType="ecore:EClass tmdl.ecore#//core/Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pValues" lowerBound="1"
        eType="ecore:EClass tmdl.ecore#//core/ParameterArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedActivityTemplate" eSuperTypes="#//ActivityTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeDistribution" lowerBound="1"
        eType="ecore:EClass san.ecore#//Distribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" eType="ecore:EClass san.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactivation" eType="ecore:EClass san.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstantaneousActivityTemplate" eSuperTypes="#//ActivityTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="MarkingTemplate" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idPlace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkingTemplateSimple" eSuperTypes="#//MarkingTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkingTemplateGlobalVariable" eSuperTypes="#//MarkingTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass san.ecore#//GlobalVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GateTemplate" abstract="true" eSuperTypes="san.ecore#//Gate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeTemplate" lowerBound="1"
        upperBound="-1" eType="#//PlaceTemplate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputGate" abstract="true" eSuperTypes="#//GateTemplate"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputGateConcrete" eSuperTypes="#//OutputGate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="case" lowerBound="1" eType="ecore:EClass san.ecore#//Case"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputGateTemplate" eSuperTypes="#//OutputGate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        upperBound="-1" eType="#//ActivityTemplate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputGateTemplate" eSuperTypes="#//GateTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
        eType="ecore:EClass san.ecore#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        upperBound="-1" eType="#//ActivityTemplate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcTemplate" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputArc" eSuperTypes="#//ArcTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass san.ecore#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ActivityTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateSource" eType="#//PlaceTemplate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputArc" eSuperTypes="#//ArcTemplate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ActivityTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass san.ecore#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templateTarget" eType="#//PlaceTemplate"/>
  </eClassifiers>
</ecore:EPackage>
