<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tmdl" nsURI="http://www.modelspartiti.org/infrastructure/tmdl"
    nsPrefix="tmdl">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eSubpackages name="scenario" nsURI="http://www.modelspartiti.org/infrastructure/tmdl/scenario"
      nsPrefix="scn">
    <eClassifiers xsi:type="ecore:EClass" name="Scenario">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variants" lowerBound="1"
          upperBound="-1" eType="#//scenario/Variant" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1"
          eType="#//scenario/Variant"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variant" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
          eType="#//core/Assignment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariantAtomic" eSuperTypes="#//scenario/Variant">
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" lowerBound="1"
          eType="#//library/TemplateAtomic"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariantComposite" eSuperTypes="#//scenario/Variant">
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" lowerBound="1"
          eType="#//library/TemplateComposite"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizations" lowerBound="1"
          upperBound="-1" eType="#//scenario/BlockRealization" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockRealization">
      <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
          eType="#//library/Block"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variant" lowerBound="1"
          eType="#//scenario/Variant"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="library" nsURI="http://www.modelspartiti.org/infrastructure/tmdl/library"
      nsPrefix="lib">
    <eClassifiers xsi:type="ecore:EClass" name="Library">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" lowerBound="1"
          upperBound="-1" eType="#//library/ModelInterface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templates" lowerBound="1"
          upperBound="-1" eType="#//library/TemplateSpecification" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelInterface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
          upperBound="-1" eType="#//library/InterfaceVariable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//core/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateSpecification" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" lowerBound="1"
          upperBound="-1" eType="#//library/ModelInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//core/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateAtomic" eSuperTypes="#//library/TemplateSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateComposite" eSuperTypes="#//library/TemplateSpecification">
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1"
          upperBound="-1" eType="#//library/CompositionRule" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" lowerBound="1"
          upperBound="-1" eType="#//library/Block" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Block">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" lowerBound="1"
          eType="#//core/Multiplicity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
          eType="#//library/ModelInterface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterfaceVariable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" lowerBound="1"
          eType="#//core/Multiplicity" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositionRule" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
          eType="#//library/InterfaceVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositionRuleAll" eSuperTypes="#//library/CompositionRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="CompositionRuleMatch" eSuperTypes="#//library/CompositionRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositionRuleForwards" eSuperTypes="#//library/CompositionRule"/>
  </eSubpackages>
  <eSubpackages name="core" nsURI="http://www.modelspartiti.org/infrastructure/tmdl/core"
      nsPrefix="core">
    <eClassifiers xsi:type="ecore:EClass" name="ConcreteModel" abstract="true" interface="true">
      <eOperations name="templatize" lowerBound="1" eType="#//core/TemplateModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateModel" abstract="true" interface="true">
      <eOperations name="concretize" lowerBound="1" eType="#//core/ConcreteModel">
        <eParameters name="parameterValues" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterSimple" eSuperTypes="#//core/Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterArray" eSuperTypes="#//core/Parameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="Assignment" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssignmentSimple" eSuperTypes="#//core/Assignment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/ParameterSimple"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssignmentArray" eSuperTypes="#//core/Assignment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/ParameterArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Multiplicity" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicityValue" eSuperTypes="#//core/Multiplicity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicityArray" eSuperTypes="#//core/Multiplicity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicityParametric" eSuperTypes="#//core/Multiplicity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/Parameter"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="http://www.modelspartiti.org/infrastructure/tmdl/expressions"
      nsPrefix="exp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpression" abstract="true"
        interface="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionInteger" abstract="true"
        interface="true" eSuperTypes="#//expressions/TemplateExpression">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="evaluate(core::Assignment.allInstances())"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionReal" abstract="true"
        interface="true" eSuperTypes="#//expressions/TemplateExpression">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="evaluate(core::Assignment.allInstances())"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBoolean" abstract="true"
        interface="true" eSuperTypes="#//expressions/TemplateExpression">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="evaluate(core::Assignment.allInstances())"/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionIntegerLiteral"
        eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="value"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealLiteral" eSuperTypes="#//expressions/TemplateExpressionReal">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="value"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBoolaenLiteral"
        eSuperTypes="#//expressions/TemplateExpressionBoolean">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="value"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionIntegerFromReal"
        eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp.evaluate(assignments).floor()"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionReal"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealFromInteger"
        eSuperTypes="#//expressions/TemplateExpressionReal">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionInteger"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionParameterSimple"
        eSuperTypes="#//expressions/TemplateExpressionReal">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="assignments->select(as | as.oclIsTypeOf(core::AssignmentSimple))&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->select(a | a.oclAsType(core::AssignmentSimple).parameter = self.parameter)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->asSequence()->first().oclAsType(core::AssignmentSimple).value"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/ParameterSimple"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionParameterArrayValueAt"
        eSuperTypes="#//expressions/TemplateExpressionReal">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="assignments->select(as | as.oclIsTypeOf(core::AssignmentArray))&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->select(a | a.oclAsType(core::AssignmentArray).parameter = self.parameter)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->asSequence()->first().oclAsType(core::AssignmentArray).values&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->at(position.evaluate(assignments))"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/ParameterArray"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
          eType="#//expressions/TemplateExpressionInteger" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionParameterArraySize"
        eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="assignments->select(as | as.oclIsTypeOf(core::AssignmentArray))&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->select(a | a.oclAsType(core::AssignmentArray).parameter = self.parameter)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->asSequence()->first().oclAsType(core::AssignmentArray).values&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;->size()"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/ParameterArray"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionArrayAggregate"
        eSuperTypes="#//expressions/TemplateExpressionReal">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="&#xA;&#x9;&#x9;&#x9;&#x9;let array = assignments->select(as | as.oclIsTypeOf(core::AssignmentArray))&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;->select(a | a.oclAsType(core::AssignmentArray).parameter = self.parameter)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;->asSequence()->first().oclAsType(core::AssignmentArray).values&#xA;&#x9;&#x9;&#x9;&#x9;in&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;if function = ArrayAggregateKind::sum then array->sum()&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;else if function = ArrayAggregateKind::min then array->min()&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;else if function = ArrayAggregateKind::max then array->max()&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;array->sum()/array->size()&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;endif endif endif"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//core/ParameterArray"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" lowerBound="1"
          eType="#//expressions/ArrayAggregateKind"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArrayAggregateKind">
      <eLiterals name="min" value="1"/>
      <eLiterals name="max" value="2"/>
      <eLiterals name="avg" value="3"/>
      <eLiterals name="sum" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealBinaryOperation"
        abstract="true" interface="true" eSuperTypes="#//expressions/TemplateExpressionReal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1"
          eType="#//expressions/TemplateExpressionReal" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" lowerBound="1"
          eType="#//expressions/TemplateExpressionReal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealSum" eSuperTypes="#//expressions/TemplateExpressionRealBinaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments) + exp2.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealSubtract" eSuperTypes="#//expressions/TemplateExpressionRealBinaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments) - exp2.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealMultiply" eSuperTypes="#//expressions/TemplateExpressionRealBinaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments) * exp2.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealDivide" eSuperTypes="#//expressions/TemplateExpressionRealBinaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments) / exp2.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealModulo" eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments).mod(exp2.evaluate(assignments))"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1"
          eType="#//expressions/TemplateExpressionInteger" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" lowerBound="1"
          eType="#//expressions/TemplateExpressionInteger" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealUnary" abstract="true"
        interface="true" eSuperTypes="#//expressions/TemplateExpressionReal">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionReal"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealFloor" eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp.evaluate(assignments).floor()"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionReal"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealCeil" eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="&#xA;&#x9;&#x9;&#x9;&#x9;let n = exp.evaluate(assignments) in&#xA;&#x9;&#x9;&#x9;&#x9;if n.floor() = n.round() then n.floor()+1&#xA;&#x9;&#x9;&#x9;&#x9;else n.round() endif"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionReal"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealRound" eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp.evaluate(assignments).round()"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionReal"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionRealIfThenElse"
        eSuperTypes="#//expressions/TemplateExpressionReal">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="&#xA;&#x9;&#x9;&#x9;&#x9;if condition.evaluate(assignments)&#xA;&#x9;&#x9;&#x9;&#x9;then ifTrue.evaluate(assignments)&#xA;&#x9;&#x9;&#x9;&#x9;else ifFalse.evaluate(assignments)&#xA;&#x9;&#x9;&#x9;&#x9;endif"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//expressions/TemplateExpressionBoolean" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifTrue" lowerBound="1"
          eType="#//expressions/TemplateExpressionReal" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ifFalse" lowerBound="1"
          eType="#//expressions/TemplateExpressionReal" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBooleanUnaryOperation"
        abstract="true" interface="true" eSuperTypes="#//expressions/TemplateExpressionBoolean">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionBoolean"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBooleanNot" eSuperTypes="#//expressions/TemplateExpressionBooleanUnaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="not exp.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBooleanToInteger"
        eSuperTypes="#//expressions/TemplateExpressionInteger">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp" lowerBound="1" eType="#//expressions/TemplateExpressionBoolean"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBooleanBinaryOperation"
        abstract="true" interface="true" eSuperTypes="#//expressions/TemplateExpressionBoolean">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp1" lowerBound="1"
          eType="#//expressions/TemplateExpressionBoolean" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exp2" lowerBound="1"
          eType="#//expressions/TemplateExpressionBoolean" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBooleanAnd" eSuperTypes="#//expressions/TemplateExpressionBooleanBinaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments) and exp2.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateExpressionBooleanOr" eSuperTypes="#//expressions/TemplateExpressionBooleanBinaryOperation">
      <eOperations name="evaluate" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
          <details key="body" value="exp1.evaluate(assignments) or exp2.evaluate(assignments)"/>
        </eAnnotations>
        <eParameters name="assignments" ordered="false" upperBound="-1" eType="#//core/Assignment"/>
      </eOperations>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
