<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tmdl" nsURI="http://www.modelspartiti.org/infrastructure/tmdl"
    nsPrefix="tmdl">
  <eClassifiers xsi:type="ecore:EClass" name="TMDLSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" lowerBound="1"
        eType="#//Library" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="#//Scenario"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" lowerBound="1"
        upperBound="-1" eType="#//TemplateSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//ModelInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" lowerBound="1"
        upperBound="-1" eType="#//Variant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Variant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateSpecification" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metric"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//ModelInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateAtomic" eSuperTypes="#//TemplateSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TemplateComposite" eSuperTypes="#//TemplateSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//CompositionRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bind" upperBound="-1" eType="#//Parambinding"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submodules" lowerBound="1"
        upperBound="-1" eType="#//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//TemplateSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mult" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" upperBound="-1"
        eType="#//ModelInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" lowerBound="1"
        eType="#//TemplateSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizations" upperBound="-1"
        eType="#//BlockRealization" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockRealization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Variant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mult" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="#//Block"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="#//StateMetavariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelInterfSimple" eSuperTypes="#//ModelInterface"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelInterfArray" eSuperTypes="#//ModelInterface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mult" lowerBound="1" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionRule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//StateMetavariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionRuleForwards" eSuperTypes="#//CompositionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//CompItem"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionRuleAll" eSuperTypes="#//CompositionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" upperBound="-1"
        eType="#//CompItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositionRuleMatch" eSuperTypes="#//CompositionRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" upperBound="-1"
        eType="#//CompItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//ModelInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//Block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ids" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueInt" eSuperTypes="#//Value #//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueDouble" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueArray" abstract="true" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueArrayInt" eSuperTypes="#//ValueArray #//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ValueInt" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueArrayDouble" eSuperTypes="#//ValueArray">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//ValueDouble" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" lowerBound="1"
        eType="#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametric" eSuperTypes="#//Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parambinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minWorkingObs" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obsPoints" lowerBound="1"
        upperBound="-1" eType="#//StateMetavariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Availability" eSuperTypes="#//Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculation" lowerBound="1"
        eType="#//AvailabilityCalc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reliability" eSuperTypes="#//Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculation" lowerBound="1"
        eType="#//ReliabilityCalc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeanTimeToFailure" eSuperTypes="#//Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculation" lowerBound="1"
        eType="#//MeanTimeToFailureCalc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AvailabilityCalc">
    <eLiterals name="instantOfTime"/>
    <eLiterals name="timeAveraged" value="1"/>
    <eLiterals name="steadyState" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReliabilityCalc">
    <eLiterals name="instantOfTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MeanTimeToFailureCalc">
    <eLiterals name="intervalOfTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMetavariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mult" eType="#//Parametric"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
  </eClassifiers>
</ecore:EPackage>
