/**
 *
 * $Id$
 */
package tmdl.core.validation;

import org.eclipse.emf.common.util.EList;

import tmdl.core.ParameterArray;

/**
 * A sample validator interface for {@link tmdl.core.AssignmentArray}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssignmentArrayValidator {
	boolean validate();

	boolean validateParameter(ParameterArray value);
	boolean validateValues(EList<Double> value);

	boolean validateValue(EList<Double> value);
}
