/**
 *
 * $Id$
 */
package tmdl.core.validation;

import tmdl.core.AggregateFunctionKind;
import tmdl.core.Parameter;

/**
 * A sample validator interface for {@link tmdl.core.ParameterExpressionAggregate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParameterExpressionAggregateValidator {
	boolean validate();

	boolean validateParameter(Parameter value);
	boolean validateFunction(AggregateFunctionKind value);
}
