/**
 *
 * $Id$
 */
package san.validation;

import san.Place;

/**
 * A sample validator interface for {@link san.ExpressionMarking}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpressionMarkingValidator {
	boolean validate();

	boolean validatePlace(Place value);
}
