/**
 *
 * $Id$
 */
package san.validation;

import org.eclipse.emf.common.util.EList;

import san.Activity;
import san.Expression;
import san.Place;

/**
 * A sample validator interface for {@link san.Gate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GateValidator {
	boolean validate();

	boolean validateFunction(Expression value);
	boolean validatePlaces(EList<Place> value);

	boolean validateActivity(Activity value);
}
