/**
 *
 * $Id$
 */
package san.validation;

import san.Marking;

/**
 * A sample validator interface for {@link san.Place}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlaceValidator {
	boolean validate();

	boolean validateMarking(Marking value);
}
