/**
 *
 * $Id$
 */
package san.validation;

import org.eclipse.emf.common.util.EList;

import san.Activity;
import san.Arc;
import san.Expression;
import san.Gate;
import san.GlobalVariable;
import san.Place;

/**
 * A sample validator interface for {@link san.SAN}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SANValidator {
	boolean validate();

	boolean validatePlaces(EList<Place> value);
	boolean validateName(String value);
	boolean validateActivities(EList<Activity> value);
	boolean validateGlobalVariables(EList<GlobalVariable> value);
	boolean validateArcs(EList<Arc> value);
	boolean validateGates(EList<Gate> value);
	boolean validateInitialization(EList<Expression> value);
}
