/**
 *
 * $Id$
 */
package sant.validation;

import org.eclipse.emf.common.util.EList;
import sant.ExpressionSegment;

import tmdl.expressions.TemplateExpressionInteger;

/**
 * A sample validator interface for {@link sant.ExpressionLoop}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpressionLoopValidator {
	boolean validate();

	boolean validateBegin(TemplateExpressionInteger value);
	boolean validateEnd(TemplateExpressionInteger value);
	boolean validateDo(EList<ExpressionSegment> value);

	boolean validateDo(ExpressionSegment value);
}
