/**
 *
 * $Id$
 */
package sant.validation;

import sant.ExpressionSegment;

import tmdl.expressions.TemplateExpressionBoolean;

/**
 * A sample validator interface for {@link sant.ExpressionIfThenElse}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpressionIfThenElseValidator {
	boolean validate();

	boolean validateCondition(TemplateExpressionBoolean value);
	boolean validateIfTrue(ExpressionSegment value);
	boolean validateIfFalse(ExpressionSegment value);
}
