/**
 *
 * $Id$
 */
package sant.validation;

import org.eclipse.emf.common.util.EList;

import sant.Activity;
import sant.Arc;
import sant.Expression;
import sant.Gate;
import sant.GlobalVariable;
import sant.Place;

import tmdl.core.Parameter;

/**
 * A sample validator interface for {@link sant.SANT}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SANTValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateParameters(EList<Parameter> value);
	boolean validatePlaces(EList<Place> value);
	boolean validateActivities(EList<Activity> value);
	boolean validateGlobalVariables(EList<GlobalVariable> value);
	boolean validateArcs(EList<Arc> value);
	boolean validateGates(EList<Gate> value);
	boolean validateInitialization(EList<Expression> value);
}
